/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CartItemListRelationFilter } from "../../cartItem/base/CartItemListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { OrderItemListRelationFilter } from "../../orderItem/base/OrderItemListRelationFilter";
import { ColorListRelationFilter } from "../../color/base/ColorListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { DecimalFilter } from "../../util/DecimalFilter";
import { IntFilter } from "../../util/IntFilter";
import { SizeListRelationFilter } from "../../size/base/SizeListRelationFilter";
import { TimerWhereUniqueInput } from "../../timer/base/TimerWhereUniqueInput";
import { ProductVariantListRelationFilter } from "../../productVariant/base/ProductVariantListRelationFilter";

@InputType()
class ProductWhereInput {
  @ApiProperty({
    required: false,
    type: () => CartItemListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CartItemListRelationFilter)
  @IsOptional()
  @Field(() => CartItemListRelationFilter, {
    nullable: true,
  })
  cartItem?: CartItemListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => OrderItemListRelationFilter,
  })
  @ValidateNested()
  @Type(() => OrderItemListRelationFilter)
  @IsOptional()
  @Field(() => OrderItemListRelationFilter, {
    nullable: true,
  })
  cartItems?: OrderItemListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ColorListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ColorListRelationFilter)
  @IsOptional()
  @Field(() => ColorListRelationFilter, {
    nullable: true,
  })
  color?: ColorListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  description?: StringFilter;

  @ApiProperty({
    required: false,
    type: DecimalFilter,
  })
  @Type(() => DecimalFilter)
  @IsOptional()
  @Field(() => DecimalFilter, {
    nullable: true,
  })
  discount?: DecimalFilter;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  images?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  name?: StringFilter;

  @ApiProperty({
    required: false,
    type: DecimalFilter,
  })
  @Type(() => DecimalFilter)
  @IsOptional()
  @Field(() => DecimalFilter, {
    nullable: true,
  })
  price?: DecimalFilter;

  @ApiProperty({
    required: false,
    type: () => SizeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SizeListRelationFilter)
  @IsOptional()
  @Field(() => SizeListRelationFilter, {
    nullable: true,
  })
  size?: SizeListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TimerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TimerWhereUniqueInput)
  @IsOptional()
  @Field(() => TimerWhereUniqueInput, {
    nullable: true,
  })
  timer?: TimerWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ProductVariantListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProductVariantListRelationFilter)
  @IsOptional()
  @Field(() => ProductVariantListRelationFilter, {
    nullable: true,
  })
  variants?: ProductVariantListRelationFilter;
}

export { ProductWhereInput as ProductWhereInput };
