/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CartItemCreateNestedManyWithoutProductsInput } from "./CartItemCreateNestedManyWithoutProductsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { OrderItemCreateNestedManyWithoutProductsInput } from "./OrderItemCreateNestedManyWithoutProductsInput";
import { ColorCreateNestedManyWithoutProductsInput } from "./ColorCreateNestedManyWithoutProductsInput";
import { Decimal } from "decimal.js";
import { SizeCreateNestedManyWithoutProductsInput } from "./SizeCreateNestedManyWithoutProductsInput";
import { TimerWhereUniqueInput } from "../../timer/base/TimerWhereUniqueInput";
import { ProductVariantCreateNestedManyWithoutProductsInput } from "./ProductVariantCreateNestedManyWithoutProductsInput";

@InputType()
class ProductCreateInput {
  @ApiProperty({
    required: false,
    type: () => CartItemCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => CartItemCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => CartItemCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  cartItem?: CartItemCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => OrderItemCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => OrderItemCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => OrderItemCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  cartItems?: OrderItemCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => ColorCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ColorCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ColorCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  color?: ColorCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  description!: string;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Float)
  discount!: Decimal;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  images!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Float)
  price!: Decimal;

  @ApiProperty({
    required: false,
    type: () => SizeCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => SizeCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => SizeCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  size?: SizeCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => TimerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TimerWhereUniqueInput)
  @IsOptional()
  @Field(() => TimerWhereUniqueInput, {
    nullable: true,
  })
  timer?: TimerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ProductVariantCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductVariantCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductVariantCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  variants?: ProductVariantCreateNestedManyWithoutProductsInput;
}

export { ProductCreateInput as ProductCreateInput };
