/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Product as PrismaProduct,
  CartItem as PrismaCartItem,
  OrderItem as PrismaOrderItem,
  Color as PrismaColor,
  Size as PrismaSize,
  ProductVariant as PrismaProductVariant,
  Timer as PrismaTimer,
} from "@prisma/client";

export class ProductServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ProductCountArgs, "select">): Promise<number> {
    return this.prisma.product.count(args);
  }

  async products(args: Prisma.ProductFindManyArgs): Promise<PrismaProduct[]> {
    return this.prisma.product.findMany(args);
  }
  async product(
    args: Prisma.ProductFindUniqueArgs
  ): Promise<PrismaProduct | null> {
    return this.prisma.product.findUnique(args);
  }
  async createProduct(args: Prisma.ProductCreateArgs): Promise<PrismaProduct> {
    return this.prisma.product.create(args);
  }
  async updateProduct(args: Prisma.ProductUpdateArgs): Promise<PrismaProduct> {
    return this.prisma.product.update(args);
  }
  async deleteProduct(args: Prisma.ProductDeleteArgs): Promise<PrismaProduct> {
    return this.prisma.product.delete(args);
  }

  async findCartItem(
    parentId: number,
    args: Prisma.CartItemFindManyArgs
  ): Promise<PrismaCartItem[]> {
    return this.prisma.product
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .cartItem(args);
  }

  async findCartItems(
    parentId: number,
    args: Prisma.OrderItemFindManyArgs
  ): Promise<PrismaOrderItem[]> {
    return this.prisma.product
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .cartItems(args);
  }

  async findColor(
    parentId: number,
    args: Prisma.ColorFindManyArgs
  ): Promise<PrismaColor[]> {
    return this.prisma.product
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .color(args);
  }

  async findSize(
    parentId: number,
    args: Prisma.SizeFindManyArgs
  ): Promise<PrismaSize[]> {
    return this.prisma.product
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .size(args);
  }

  async findVariants(
    parentId: number,
    args: Prisma.ProductVariantFindManyArgs
  ): Promise<PrismaProductVariant[]> {
    return this.prisma.product
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .variants(args);
  }

  async getTimer(parentId: number): Promise<PrismaTimer | null> {
    return this.prisma.product
      .findUnique({
        where: { id: parentId },
      })
      .timer();
  }
}
