/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProductService } from "../product.service";
import { ProductCreateInput } from "./ProductCreateInput";
import { Product } from "./Product";
import { ProductFindManyArgs } from "./ProductFindManyArgs";
import { ProductWhereUniqueInput } from "./ProductWhereUniqueInput";
import { ProductUpdateInput } from "./ProductUpdateInput";
import { CartItemFindManyArgs } from "../../cartItem/base/CartItemFindManyArgs";
import { CartItem } from "../../cartItem/base/CartItem";
import { CartItemWhereUniqueInput } from "../../cartItem/base/CartItemWhereUniqueInput";
import { OrderItemFindManyArgs } from "../../orderItem/base/OrderItemFindManyArgs";
import { OrderItem } from "../../orderItem/base/OrderItem";
import { OrderItemWhereUniqueInput } from "../../orderItem/base/OrderItemWhereUniqueInput";
import { ColorFindManyArgs } from "../../color/base/ColorFindManyArgs";
import { Color } from "../../color/base/Color";
import { ColorWhereUniqueInput } from "../../color/base/ColorWhereUniqueInput";
import { SizeFindManyArgs } from "../../size/base/SizeFindManyArgs";
import { Size } from "../../size/base/Size";
import { SizeWhereUniqueInput } from "../../size/base/SizeWhereUniqueInput";
import { ProductVariantFindManyArgs } from "../../productVariant/base/ProductVariantFindManyArgs";
import { ProductVariant } from "../../productVariant/base/ProductVariant";
import { ProductVariantWhereUniqueInput } from "../../productVariant/base/ProductVariantWhereUniqueInput";

export class ProductControllerBase {
  constructor(protected readonly service: ProductService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Product })
  async createProduct(
    @common.Body() data: ProductCreateInput
  ): Promise<Product> {
    return await this.service.createProduct({
      data: {
        ...data,

        timer: data.timer
          ? {
              connect: data.timer,
            }
          : undefined,
      },
      select: {
        description: true,
        discount: true,
        id: true,
        images: true,
        name: true,
        price: true,

        timer: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Product] })
  @ApiNestedQuery(ProductFindManyArgs)
  async products(@common.Req() request: Request): Promise<Product[]> {
    const args = plainToClass(ProductFindManyArgs, request.query);
    return this.service.products({
      ...args,
      select: {
        description: true,
        discount: true,
        id: true,
        images: true,
        name: true,
        price: true,

        timer: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async product(
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Product | null> {
    const result = await this.service.product({
      where: params,
      select: {
        description: true,
        discount: true,
        id: true,
        images: true,
        name: true,
        price: true,

        timer: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProduct(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() data: ProductUpdateInput
  ): Promise<Product | null> {
    try {
      return await this.service.updateProduct({
        where: params,
        data: {
          ...data,

          timer: data.timer
            ? {
                connect: data.timer,
              }
            : undefined,
        },
        select: {
          description: true,
          discount: true,
          id: true,
          images: true,
          name: true,
          price: true,

          timer: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProduct(
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Product | null> {
    try {
      return await this.service.deleteProduct({
        where: params,
        select: {
          description: true,
          discount: true,
          id: true,
          images: true,
          name: true,
          price: true,

          timer: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/cartItem")
  @ApiNestedQuery(CartItemFindManyArgs)
  async findCartItem(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<CartItem[]> {
    const query = plainToClass(CartItemFindManyArgs, request.query);
    const results = await this.service.findCartItem(params.id, {
      ...query,
      select: {
        cart: {
          select: {
            id: true,
          },
        },

        color: {
          select: {
            id: true,
          },
        },

        id: true,
        price: true,

        product: {
          select: {
            id: true,
          },
        },

        quantity: true,

        size: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/cartItem")
  async connectCartItem(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: CartItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cartItem: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/cartItem")
  async updateCartItem(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: CartItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cartItem: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/cartItem")
  async disconnectCartItem(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: CartItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cartItem: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/cartItems")
  @ApiNestedQuery(OrderItemFindManyArgs)
  async findCartItems(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<OrderItem[]> {
    const query = plainToClass(OrderItemFindManyArgs, request.query);
    const results = await this.service.findCartItems(params.id, {
      ...query,
      select: {
        cart: {
          select: {
            id: true,
          },
        },

        id: true,
        price: true,

        product: {
          select: {
            id: true,
          },
        },

        quantity: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/cartItems")
  async connectCartItems(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: OrderItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cartItems: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/cartItems")
  async updateCartItems(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: OrderItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cartItems: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/cartItems")
  async disconnectCartItems(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: OrderItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cartItems: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/color")
  @ApiNestedQuery(ColorFindManyArgs)
  async findColor(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Color[]> {
    const query = plainToClass(ColorFindManyArgs, request.query);
    const results = await this.service.findColor(params.id, {
      ...query,
      select: {
        color: true,
        colorGuid: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/color")
  async connectColor(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: ColorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      color: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/color")
  async updateColor(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: ColorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      color: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/color")
  async disconnectColor(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: ColorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      color: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/size")
  @ApiNestedQuery(SizeFindManyArgs)
  async findSize(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Size[]> {
    const query = plainToClass(SizeFindManyArgs, request.query);
    const results = await this.service.findSize(params.id, {
      ...query,
      select: {
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        size: true,
        sizeGuid: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/size")
  async connectSize(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: SizeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      size: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/size")
  async updateSize(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: SizeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      size: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/size")
  async disconnectSize(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: SizeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      size: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/variants")
  @ApiNestedQuery(ProductVariantFindManyArgs)
  async findVariants(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<ProductVariant[]> {
    const query = plainToClass(ProductVariantFindManyArgs, request.query);
    const results = await this.service.findVariants(params.id, {
      ...query,
      select: {
        color: {
          select: {
            id: true,
          },
        },

        id: true,
        price: true,

        product: {
          select: {
            id: true,
          },
        },

        quantity: true,

        size: {
          select: {
            id: true,
          },
        },

        sku: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/variants")
  async connectVariants(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: ProductVariantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variants: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/variants")
  async updateVariants(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: ProductVariantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variants: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/variants")
  async disconnectVariants(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: ProductVariantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variants: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }
}
