/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CartItem } from "../../cartItem/base/CartItem";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  Max,
  IsInt,
} from "class-validator";
import { Type } from "class-transformer";
import { OrderItem } from "../../orderItem/base/OrderItem";
import { Color } from "../../color/base/Color";
import { Decimal } from "decimal.js";
import { Size } from "../../size/base/Size";
import { Timer } from "../../timer/base/Timer";
import { ProductVariant } from "../../productVariant/base/ProductVariant";

@ObjectType()
class Product {
  @ApiProperty({
    required: false,
    type: () => [CartItem],
  })
  @ValidateNested()
  @Type(() => CartItem)
  @IsOptional()
  cartItem?: Array<CartItem>;

  @ApiProperty({
    required: false,
    type: () => [OrderItem],
  })
  @ValidateNested()
  @Type(() => OrderItem)
  @IsOptional()
  cartItems?: Array<OrderItem>;

  @ApiProperty({
    required: false,
    type: () => [Color],
  })
  @ValidateNested()
  @Type(() => Color)
  @IsOptional()
  color?: Array<Color>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  description!: string;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Float)
  discount!: Decimal;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  id!: number;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  images!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Float)
  price!: Decimal;

  @ApiProperty({
    required: false,
    type: () => [Size],
  })
  @ValidateNested()
  @Type(() => Size)
  @IsOptional()
  size?: Array<Size>;

  @ApiProperty({
    required: false,
    type: () => Timer,
  })
  @ValidateNested()
  @Type(() => Timer)
  @IsOptional()
  timer?: Timer | null;

  @ApiProperty({
    required: false,
    type: () => [ProductVariant],
  })
  @ValidateNested()
  @Type(() => ProductVariant)
  @IsOptional()
  variants?: Array<ProductVariant>;
}

export { Product as Product };
