/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CartItemUpdateManyWithoutProductsInput } from "./CartItemUpdateManyWithoutProductsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { OrderItemUpdateManyWithoutProductsInput } from "./OrderItemUpdateManyWithoutProductsInput";
import { ColorUpdateManyWithoutProductsInput } from "./ColorUpdateManyWithoutProductsInput";
import { Decimal } from "decimal.js";
import { SizeUpdateManyWithoutProductsInput } from "./SizeUpdateManyWithoutProductsInput";
import { TimerWhereUniqueInput } from "../../timer/base/TimerWhereUniqueInput";
import { ProductVariantUpdateManyWithoutProductsInput } from "./ProductVariantUpdateManyWithoutProductsInput";

@InputType()
class ProductUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CartItemUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => CartItemUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => CartItemUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  cartItem?: CartItemUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => OrderItemUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => OrderItemUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => OrderItemUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  cartItems?: OrderItemUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => ColorUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ColorUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ColorUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  color?: ColorUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  discount?: Decimal;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  images?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  price?: Decimal;

  @ApiProperty({
    required: false,
    type: () => SizeUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => SizeUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => SizeUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  size?: SizeUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => TimerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TimerWhereUniqueInput)
  @IsOptional()
  @Field(() => TimerWhereUniqueInput, {
    nullable: true,
  })
  timer?: TimerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ProductVariantUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductVariantUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductVariantUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  variants?: ProductVariantUpdateManyWithoutProductsInput;
}

export { ProductUpdateInput as ProductUpdateInput };
