/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Color } from "./Color";
import { ColorCountArgs } from "./ColorCountArgs";
import { ColorFindManyArgs } from "./ColorFindManyArgs";
import { ColorFindUniqueArgs } from "./ColorFindUniqueArgs";
import { CreateColorArgs } from "./CreateColorArgs";
import { UpdateColorArgs } from "./UpdateColorArgs";
import { DeleteColorArgs } from "./DeleteColorArgs";
import { CartItemFindManyArgs } from "../../cartItem/base/CartItemFindManyArgs";
import { CartItem } from "../../cartItem/base/CartItem";
import { ProductVariantFindManyArgs } from "../../productVariant/base/ProductVariantFindManyArgs";
import { ProductVariant } from "../../productVariant/base/ProductVariant";
import { Product } from "../../product/base/Product";
import { ColorService } from "../color.service";
@graphql.Resolver(() => Color)
export class ColorResolverBase {
  constructor(protected readonly service: ColorService) {}

  async _colorsMeta(
    @graphql.Args() args: ColorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Color])
  async colors(@graphql.Args() args: ColorFindManyArgs): Promise<Color[]> {
    return this.service.colors(args);
  }

  @graphql.Query(() => Color, { nullable: true })
  async color(
    @graphql.Args() args: ColorFindUniqueArgs
  ): Promise<Color | null> {
    const result = await this.service.color(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Color)
  async createColor(@graphql.Args() args: CreateColorArgs): Promise<Color> {
    return await this.service.createColor({
      ...args,
      data: {
        ...args.data,

        product: {
          connect: args.data.product,
        },
      },
    });
  }

  @graphql.Mutation(() => Color)
  async updateColor(
    @graphql.Args() args: UpdateColorArgs
  ): Promise<Color | null> {
    try {
      return await this.service.updateColor({
        ...args,
        data: {
          ...args.data,

          product: {
            connect: args.data.product,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Color)
  async deleteColor(
    @graphql.Args() args: DeleteColorArgs
  ): Promise<Color | null> {
    try {
      return await this.service.deleteColor(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [CartItem], { name: "cartItem" })
  async findCartItem(
    @graphql.Parent() parent: Color,
    @graphql.Args() args: CartItemFindManyArgs
  ): Promise<CartItem[]> {
    const results = await this.service.findCartItem(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [ProductVariant], { name: "variants" })
  async findVariants(
    @graphql.Parent() parent: Color,
    @graphql.Args() args: ProductVariantFindManyArgs
  ): Promise<ProductVariant[]> {
    const results = await this.service.findVariants(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  async getProduct(@graphql.Parent() parent: Color): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
