/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ColorService } from "../color.service";
import { ColorCreateInput } from "./ColorCreateInput";
import { Color } from "./Color";
import { ColorFindManyArgs } from "./ColorFindManyArgs";
import { ColorWhereUniqueInput } from "./ColorWhereUniqueInput";
import { ColorUpdateInput } from "./ColorUpdateInput";
import { CartItemFindManyArgs } from "../../cartItem/base/CartItemFindManyArgs";
import { CartItem } from "../../cartItem/base/CartItem";
import { CartItemWhereUniqueInput } from "../../cartItem/base/CartItemWhereUniqueInput";
import { ProductVariantFindManyArgs } from "../../productVariant/base/ProductVariantFindManyArgs";
import { ProductVariant } from "../../productVariant/base/ProductVariant";
import { ProductVariantWhereUniqueInput } from "../../productVariant/base/ProductVariantWhereUniqueInput";

export class ColorControllerBase {
  constructor(protected readonly service: ColorService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Color })
  async createColor(@common.Body() data: ColorCreateInput): Promise<Color> {
    return await this.service.createColor({
      data: {
        ...data,

        product: {
          connect: data.product,
        },
      },
      select: {
        color: true,
        colorGuid: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Color] })
  @ApiNestedQuery(ColorFindManyArgs)
  async colors(@common.Req() request: Request): Promise<Color[]> {
    const args = plainToClass(ColorFindManyArgs, request.query);
    return this.service.colors({
      ...args,
      select: {
        color: true,
        colorGuid: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Color })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async color(
    @common.Param() params: ColorWhereUniqueInput
  ): Promise<Color | null> {
    const result = await this.service.color({
      where: params,
      select: {
        color: true,
        colorGuid: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Color })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateColor(
    @common.Param() params: ColorWhereUniqueInput,
    @common.Body() data: ColorUpdateInput
  ): Promise<Color | null> {
    try {
      return await this.service.updateColor({
        where: params,
        data: {
          ...data,

          product: {
            connect: data.product,
          },
        },
        select: {
          color: true,
          colorGuid: true,
          id: true,

          product: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Color })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteColor(
    @common.Param() params: ColorWhereUniqueInput
  ): Promise<Color | null> {
    try {
      return await this.service.deleteColor({
        where: params,
        select: {
          color: true,
          colorGuid: true,
          id: true,

          product: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/cartItem")
  @ApiNestedQuery(CartItemFindManyArgs)
  async findCartItem(
    @common.Req() request: Request,
    @common.Param() params: ColorWhereUniqueInput
  ): Promise<CartItem[]> {
    const query = plainToClass(CartItemFindManyArgs, request.query);
    const results = await this.service.findCartItem(params.id, {
      ...query,
      select: {
        cart: {
          select: {
            id: true,
          },
        },

        color: {
          select: {
            id: true,
          },
        },

        id: true,
        price: true,

        product: {
          select: {
            id: true,
          },
        },

        quantity: true,

        size: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/cartItem")
  async connectCartItem(
    @common.Param() params: ColorWhereUniqueInput,
    @common.Body() body: CartItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cartItem: {
        connect: body,
      },
    };
    await this.service.updateColor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/cartItem")
  async updateCartItem(
    @common.Param() params: ColorWhereUniqueInput,
    @common.Body() body: CartItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cartItem: {
        set: body,
      },
    };
    await this.service.updateColor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/cartItem")
  async disconnectCartItem(
    @common.Param() params: ColorWhereUniqueInput,
    @common.Body() body: CartItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cartItem: {
        disconnect: body,
      },
    };
    await this.service.updateColor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/variants")
  @ApiNestedQuery(ProductVariantFindManyArgs)
  async findVariants(
    @common.Req() request: Request,
    @common.Param() params: ColorWhereUniqueInput
  ): Promise<ProductVariant[]> {
    const query = plainToClass(ProductVariantFindManyArgs, request.query);
    const results = await this.service.findVariants(params.id, {
      ...query,
      select: {
        color: {
          select: {
            id: true,
          },
        },

        id: true,
        price: true,

        product: {
          select: {
            id: true,
          },
        },

        quantity: true,

        size: {
          select: {
            id: true,
          },
        },

        sku: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/variants")
  async connectVariants(
    @common.Param() params: ColorWhereUniqueInput,
    @common.Body() body: ProductVariantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variants: {
        connect: body,
      },
    };
    await this.service.updateColor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/variants")
  async updateVariants(
    @common.Param() params: ColorWhereUniqueInput,
    @common.Body() body: ProductVariantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variants: {
        set: body,
      },
    };
    await this.service.updateColor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/variants")
  async disconnectVariants(
    @common.Param() params: ColorWhereUniqueInput,
    @common.Body() body: ProductVariantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variants: {
        disconnect: body,
      },
    };
    await this.service.updateColor({
      where: params,
      data,
      select: { id: true },
    });
  }
}
