/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SizeService } from "../size.service";
import { SizeCreateInput } from "./SizeCreateInput";
import { Size } from "./Size";
import { SizeFindManyArgs } from "./SizeFindManyArgs";
import { SizeWhereUniqueInput } from "./SizeWhereUniqueInput";
import { SizeUpdateInput } from "./SizeUpdateInput";
import { CartItemFindManyArgs } from "../../cartItem/base/CartItemFindManyArgs";
import { CartItem } from "../../cartItem/base/CartItem";
import { CartItemWhereUniqueInput } from "../../cartItem/base/CartItemWhereUniqueInput";
import { ProductVariantFindManyArgs } from "../../productVariant/base/ProductVariantFindManyArgs";
import { ProductVariant } from "../../productVariant/base/ProductVariant";
import { ProductVariantWhereUniqueInput } from "../../productVariant/base/ProductVariantWhereUniqueInput";

export class SizeControllerBase {
  constructor(protected readonly service: SizeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Size })
  async createSize(@common.Body() data: SizeCreateInput): Promise<Size> {
    return await this.service.createSize({
      data: {
        ...data,

        product: {
          connect: data.product,
        },
      },
      select: {
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        size: true,
        sizeGuid: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Size] })
  @ApiNestedQuery(SizeFindManyArgs)
  async sizes(@common.Req() request: Request): Promise<Size[]> {
    const args = plainToClass(SizeFindManyArgs, request.query);
    return this.service.sizes({
      ...args,
      select: {
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        size: true,
        sizeGuid: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Size })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async size(
    @common.Param() params: SizeWhereUniqueInput
  ): Promise<Size | null> {
    const result = await this.service.size({
      where: params,
      select: {
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        size: true,
        sizeGuid: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Size })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSize(
    @common.Param() params: SizeWhereUniqueInput,
    @common.Body() data: SizeUpdateInput
  ): Promise<Size | null> {
    try {
      return await this.service.updateSize({
        where: params,
        data: {
          ...data,

          product: {
            connect: data.product,
          },
        },
        select: {
          id: true,

          product: {
            select: {
              id: true,
            },
          },

          size: true,
          sizeGuid: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Size })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSize(
    @common.Param() params: SizeWhereUniqueInput
  ): Promise<Size | null> {
    try {
      return await this.service.deleteSize({
        where: params,
        select: {
          id: true,

          product: {
            select: {
              id: true,
            },
          },

          size: true,
          sizeGuid: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/cartItem")
  @ApiNestedQuery(CartItemFindManyArgs)
  async findCartItem(
    @common.Req() request: Request,
    @common.Param() params: SizeWhereUniqueInput
  ): Promise<CartItem[]> {
    const query = plainToClass(CartItemFindManyArgs, request.query);
    const results = await this.service.findCartItem(params.id, {
      ...query,
      select: {
        cart: {
          select: {
            id: true,
          },
        },

        color: {
          select: {
            id: true,
          },
        },

        id: true,
        price: true,

        product: {
          select: {
            id: true,
          },
        },

        quantity: true,

        size: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/cartItem")
  async connectCartItem(
    @common.Param() params: SizeWhereUniqueInput,
    @common.Body() body: CartItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cartItem: {
        connect: body,
      },
    };
    await this.service.updateSize({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/cartItem")
  async updateCartItem(
    @common.Param() params: SizeWhereUniqueInput,
    @common.Body() body: CartItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cartItem: {
        set: body,
      },
    };
    await this.service.updateSize({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/cartItem")
  async disconnectCartItem(
    @common.Param() params: SizeWhereUniqueInput,
    @common.Body() body: CartItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cartItem: {
        disconnect: body,
      },
    };
    await this.service.updateSize({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/variants")
  @ApiNestedQuery(ProductVariantFindManyArgs)
  async findVariants(
    @common.Req() request: Request,
    @common.Param() params: SizeWhereUniqueInput
  ): Promise<ProductVariant[]> {
    const query = plainToClass(ProductVariantFindManyArgs, request.query);
    const results = await this.service.findVariants(params.id, {
      ...query,
      select: {
        color: {
          select: {
            id: true,
          },
        },

        id: true,
        price: true,

        product: {
          select: {
            id: true,
          },
        },

        quantity: true,

        size: {
          select: {
            id: true,
          },
        },

        sku: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/variants")
  async connectVariants(
    @common.Param() params: SizeWhereUniqueInput,
    @common.Body() body: ProductVariantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variants: {
        connect: body,
      },
    };
    await this.service.updateSize({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/variants")
  async updateVariants(
    @common.Param() params: SizeWhereUniqueInput,
    @common.Body() body: ProductVariantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variants: {
        set: body,
      },
    };
    await this.service.updateSize({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/variants")
  async disconnectVariants(
    @common.Param() params: SizeWhereUniqueInput,
    @common.Body() body: ProductVariantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variants: {
        disconnect: body,
      },
    };
    await this.service.updateSize({
      where: params,
      data,
      select: { id: true },
    });
  }
}
