/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProductVariant } from "./ProductVariant";
import { ProductVariantCountArgs } from "./ProductVariantCountArgs";
import { ProductVariantFindManyArgs } from "./ProductVariantFindManyArgs";
import { ProductVariantFindUniqueArgs } from "./ProductVariantFindUniqueArgs";
import { CreateProductVariantArgs } from "./CreateProductVariantArgs";
import { UpdateProductVariantArgs } from "./UpdateProductVariantArgs";
import { DeleteProductVariantArgs } from "./DeleteProductVariantArgs";
import { Color } from "../../color/base/Color";
import { Product } from "../../product/base/Product";
import { Size } from "../../size/base/Size";
import { ProductVariantService } from "../productVariant.service";
@graphql.Resolver(() => ProductVariant)
export class ProductVariantResolverBase {
  constructor(protected readonly service: ProductVariantService) {}

  async _productVariantsMeta(
    @graphql.Args() args: ProductVariantCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProductVariant])
  async productVariants(
    @graphql.Args() args: ProductVariantFindManyArgs
  ): Promise<ProductVariant[]> {
    return this.service.productVariants(args);
  }

  @graphql.Query(() => ProductVariant, { nullable: true })
  async productVariant(
    @graphql.Args() args: ProductVariantFindUniqueArgs
  ): Promise<ProductVariant | null> {
    const result = await this.service.productVariant(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProductVariant)
  async createProductVariant(
    @graphql.Args() args: CreateProductVariantArgs
  ): Promise<ProductVariant> {
    return await this.service.createProductVariant({
      ...args,
      data: {
        ...args.data,

        color: {
          connect: args.data.color,
        },

        product: {
          connect: args.data.product,
        },

        size: {
          connect: args.data.size,
        },
      },
    });
  }

  @graphql.Mutation(() => ProductVariant)
  async updateProductVariant(
    @graphql.Args() args: UpdateProductVariantArgs
  ): Promise<ProductVariant | null> {
    try {
      return await this.service.updateProductVariant({
        ...args,
        data: {
          ...args.data,

          color: {
            connect: args.data.color,
          },

          product: {
            connect: args.data.product,
          },

          size: {
            connect: args.data.size,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ProductVariant)
  async deleteProductVariant(
    @graphql.Args() args: DeleteProductVariantArgs
  ): Promise<ProductVariant | null> {
    try {
      return await this.service.deleteProductVariant(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Color, {
    nullable: true,
    name: "color",
  })
  async getColor(
    @graphql.Parent() parent: ProductVariant
  ): Promise<Color | null> {
    const result = await this.service.getColor(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  async getProduct(
    @graphql.Parent() parent: ProductVariant
  ): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Size, {
    nullable: true,
    name: "size",
  })
  async getSize(
    @graphql.Parent() parent: ProductVariant
  ): Promise<Size | null> {
    const result = await this.service.getSize(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
