/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ColorWhereUniqueInput } from "../../color/base/ColorWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { IntFilter } from "../../util/IntFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";
import { SizeWhereUniqueInput } from "../../size/base/SizeWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";

@InputType()
class ProductVariantWhereInput {
  @ApiProperty({
    required: false,
    type: () => ColorWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ColorWhereUniqueInput)
  @IsOptional()
  @Field(() => ColorWhereUniqueInput, {
    nullable: true,
  })
  color?: ColorWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: DecimalNullableFilter,
  })
  @Type(() => DecimalNullableFilter)
  @IsOptional()
  @Field(() => DecimalNullableFilter, {
    nullable: true,
  })
  price?: DecimalNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ProductWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @IsOptional()
  @Field(() => ProductWhereUniqueInput, {
    nullable: true,
  })
  product?: ProductWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  quantity?: IntFilter;

  @ApiProperty({
    required: false,
    type: () => SizeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SizeWhereUniqueInput)
  @IsOptional()
  @Field(() => SizeWhereUniqueInput, {
    nullable: true,
  })
  size?: SizeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  sku?: StringNullableFilter;
}

export { ProductVariantWhereInput as ProductVariantWhereInput };
